#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Screenkey manage=off
bspc rule -a copyq state=floating rectangle=800x600+0+0 center=on 

# colors
bspc config focused_border_color "#d5e0f8"
bspc config active_border_color "#d5e0f8"
bspc config normal_border_color "#7aa2f7"

# wallpaper
feh --bg-fill $HOME/downloads/wallpaper/0.png

# input
fcitx5 &

# I don't want to see this file...
rm -r ~/Downloads/

# polybar
sh $HOME/.config/polybar/launch.sh

# dunst
dunst &

# udisk
# udiskie &

# picom
picom --no-frame-pacing &

# disable touchpad
xinput set-prop "ELAN0662:00 04F3:30BC Touchpad" "Device Enabled" 0

# clipboard
copyq &
