#! /bin/sh
# bspc monitor eDP-1 -d I II III IV V VI
# bspc monitor HDMI-1 -d VII VIII VIV VV
# bspc monitor eDP-1 -d I II III IV V VI
edp=$(xrandr | grep -E 'eDP' | awk '{print $1}')
hdmi=$(xrandr | grep -E 'HDMI' | awk '{print $1}')
if xrandr | grep "HDMI" | grep " connected"; then
  xrandr --output $hdmi --mode 1920x1080 --rate 120 --primary --set "Broadcast RGB" "Full" --output $edp --off
  bspc wm -O $hdmi
  bspc monitor $hdmi -d I II III IV V VI
  sed -i 's/\(size = \s*\)[0-9]\+/\112/' ~/.config/alacritty/alacritty.toml
else
  bspc monitor $edp -d I II III IV V VI
  sed -i 's/\(size = \s*\)[0-9]\+/\19/' ~/.config/alacritty/alacritty.toml
fi

bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Screenkey manage=off
bspc rule -a copyq state=floating rectangle=800x600+0+0 center=on

bspc rule -a neovide rectangle=800x300+1114+0 state=floating
bspc rule -a Alacritty rectangle=800x300+1114+0 state=floating
bspc rule -a Brave-browser rectangle=800x300+1114+0 state=floating

bspc rule -a neovide state=tiled
bspc rule -a Alacritty state=tiled
bspc rule -a Brave-browser state=tiled

# mouse action
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# colors
bspc config focused_border_color "#c6a0f6"
bspc config active_border_color "#24273a"
bspc config normal_border_color "#24273a"

# wallpaper
feh --bg-fill $HOME/downloads/wallpaper/2.png

# input
fcitx5 &

# I don't want to see this file...
rm -r ~/Downloads/

# polybar
sh $HOME/.config/polybar/launch.sh

# dunst
dunst &

# udisk
# udiskie &

# picom
# picom --no-frame-pacing &
picom &

# disable touchpad
xinput set-prop "ELAN0662:00 04F3:30BC Touchpad" "Device Enabled" 0

# clipboard
copyq &

pgrep -x sxhkd >/dev/null || sxhkd &
