return {}
-- return {
--   {
--     "amitds1997/remote-nvim.nvim",
--     version = "*", -- This keeps it pinned to semantic releases
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "MunifTanjim/nui.nvim",
--       "rcarriga/nvim-notify",
--     },
--     config = true, -- This calls the default setup(); make sure to call it
--   },
-- }
