-- return {
--
--   "nvim-treesitter/nvim-treesitter-context",
--   event = "BufEnter",
--   enabled = true,
--   -- opts = { mode = "cursor", max_lines = 3 },
--   -- config = function(_, opts)
--   --   require("treesitter-context").setup(opts)
--   -- end,
-- }
-- return {
--   "utilyre/barbecue.nvim",
--   name = "barbecue",
--   version = "*",
--   dependencies = {
--     "SmiteshP/nvim-navic",
--     "nvim-tree/nvim-web-devicons", -- optional dependency
--   },
--   opts = {
--     -- configurations go here
--   },
-- }

return {}
